/**
 * One-off: seed enrollments for a single user so the "Kursus Saya" page has
 * something to render. Picks the first N published courses, attaches them
 * with mixed `progressPct` / `lastAccessedAt` values so all three filter tabs
 * (Semua / Sedang Dipelajari / Selesai) show data and the sort order is
 * visible.
 *
 * Run with:  npx tsx scripts/seed-my-courses.ts
 */
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma";

const TARGET_EMAIL = "faridzahran174@gmail.com";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter, log: ["error"] });

const HOUR = 60 * 60 * 1000;

type Seed = {
  progressPct: number;
  lastAccessedHoursAgo: number | null; // null = never opened
  completed: boolean;
};

// Index aligned with the first 6 PUBLISHED courses returned by the query
// below — adjust counts if there are fewer courses available.
const SEED_PROFILE: Seed[] = [
  { progressPct: 100, lastAccessedHoursAgo: 2, completed: true }, // most-recent completed → top
  { progressPct: 65, lastAccessedHoursAgo: 6, completed: false }, // mid in-progress
  { progressPct: 30, lastAccessedHoursAgo: 24, completed: false }, // early in-progress
  { progressPct: 100, lastAccessedHoursAgo: 96, completed: true }, // older completed
  { progressPct: 10, lastAccessedHoursAgo: 240, completed: false }, // older in-progress
  { progressPct: 0, lastAccessedHoursAgo: null, completed: false }, // bought, never opened
];

async function main() {
  const user = await db.user.findUnique({
    where: { email: TARGET_EMAIL },
    select: { id: true, email: true, name: true, role: true },
  });
  if (!user) {
    throw new Error(
      `No user found with email "${TARGET_EMAIL}". Sign up first, then re-run.`,
    );
  }
  console.log(`Target user: ${user.name} <${user.email}> (role=${user.role})`);

  const courses = await db.course.findMany({
    where: { status: "PUBLISHED" },
    select: { id: true, title: true },
    orderBy: [{ isFeatured: "desc" }, { createdAt: "desc" }],
    take: SEED_PROFILE.length,
  });
  if (courses.length === 0) {
    throw new Error("No PUBLISHED courses found. Seed the catalog first.");
  }
  console.log(`Found ${courses.length} published courses to attach.`);

  const now = Date.now();
  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (let i = 0; i < courses.length; i++) {
    const course = courses[i];
    const seed = SEED_PROFILE[i];

    const existing = await db.enrollment.findUnique({
      where: { userId_courseId: { userId: user.id, courseId: course.id } },
    });

    const lastAccessedAt =
      seed.lastAccessedHoursAgo === null
        ? null
        : new Date(now - seed.lastAccessedHoursAgo * HOUR);

    if (existing) {
      // Only refresh fields if they're still defaults — don't clobber real
      // progress that the user generated by clicking around.
      if (existing.progressPct === 0 && existing.lastAccessedAt === null) {
        await db.enrollment.update({
          where: { id: existing.id },
          data: {
            progressPct: seed.progressPct,
            lastAccessedAt,
            completedAt: seed.completed ? new Date(now - 2 * HOUR) : null,
          },
        });
        console.log(
          `  updated  ${course.title.slice(0, 50).padEnd(50)}  ${seed.progressPct}%`,
        );
        updated++;
      } else {
        console.log(
          `  skipped  ${course.title.slice(0, 50).padEnd(50)}  (already has progress)`,
        );
        skipped++;
      }
      continue;
    }

    await db.enrollment.create({
      data: {
        userId: user.id,
        courseId: course.id,
        progressPct: seed.progressPct,
        lastAccessedAt,
        completedAt: seed.completed ? new Date(now - 2 * HOUR) : null,
      },
    });
    console.log(
      `  created  ${course.title.slice(0, 50).padEnd(50)}  ${seed.progressPct}%`,
    );
    created++;
  }

  console.log(
    `\nDone. created=${created} updated=${updated} skipped=${skipped}`,
  );
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
